#!/bin/bash
# Instalation de nginx à partir d'un node standard
#PE-20140707
SERVICE=repository
MYNAME=${MYNAME:-install-$SERVICE.sh}
MYTMP="/tmp/.$MYNAME.$(date +%Y%m%d.%H%M%S)"
trap "rm -f $MYTMP" 0 1 2 3 5
rouge='\e[0;31m'; vert='\e[0;32m'; jaune='\e[1;33m'; bleu='\e[0;34m'; neutre='\e[0;m';
print() { color=$1; shift; if [ _$(basename $SHELL) = "_bash" ]; then echo -e "${color}$* ${neutre}"; else echo "$*"; fi; }
printstd() { print "${vert}" "$MYNAME: $*"; }
printerr() { print "${rouge}" "$MYNAME: $*" 2>&1; }
printwrn() { print "${jaune}" "$MYNAME: $*"; }
printhlp() { print "${bleu}" "$*"; }
export DEBIAN_FRONTEND=noninteractive

domain=${domain:-repository.os.gov.pf}

# Analyse des arguments:
while getopts h opt
do case "$opt" in
    h|\?) #unknown flag
       printhlp "syntaxe: $MYNAME <server_url>"
       printhlp
       printhlp "eg.   $MYNAME repository.os.gov.pf"
       printhlp
       printhlp "or:   curl -sfH \"X-Auth-Token: <X_Auth_Token>\" \\"
       printhlp "           <X-Storage-Url>/os-bootstrap/$MYNAME \\"
       printhlp "        | bash -s -- repository.os.gov.pf"
       printhlp
       printhlp "from: curl -is -H \"X-Auth-User: system:root\" \\"
       printhlp "               -H \"X-Auth-Key: testpass\" \\"
       printhlp "               http://swiftauth:8080/auth/v1.0"
       printhlp
       exit 0;;
  esac
done
shift `expr $OPTIND - 1`
! whoami | grep -qsw root && printerr "must be root to do that..." && exit 1
[ $# -ne 0 ] && domain=$1 && shift
([ $# -ne 0 ] || ! echo $domain| grep -qs "\.") \
 && printerr "bad argument... (see: -h)" && exit 1

insertLineInFile() { # syntaxe: $0 "line" fileName [numLine]
 [ -z "$2" -o ! -w $2 ] && return 1
 local n=${3:-0}
 ([ 0$n -ne 0 ] && head -n $(expr $n - 1) <$2) >$MYTMP
 echo "$1" >>$MYTMP
 tail -n +$n <$2 >>$MYTMP
 [ 0$(expr $(wc -l <$2) + 1) -eq 0$(wc -l <$MYTMP) ] \
  && cat <$MYTMP >$2
}


# verification des dependences:
! command -v gitlab-ctl >/dev/null && printerr "gitlab is not installed on this server (procedure aborted)..." && exit 1


# Configure nginx for http://repository.os.gov.pf:
CONFile=/var/opt/gitlab/nginx/etc/nginx.conf
CONFNAME=/var/opt/gitlab/nginx/etc/repository-http.conf
cat > $CONFNAME <<@@@
server {
#  listen 8000;
  server_name $domain;
  server_tokens off;     # don't show the version number, a security best practice
  root /media/cloudfuse/repository;
  index index.html index.htm;

        location / {
		try_files \$uri \$uri/ =404;
                autoindex on;
        }

}
@@@


# and add the include $CONFNAME in nginx.conf:
[ -d /etc/nginx ] || ln -s /var/opt/gitlab/nginx/etc /etc/nginx
if ! grep -Pvs "[ \t]*#" <$CONFile| grep -nsw include| grep -qs $CONFNAME; then
  num=$(grep -nsw include <$CONFile| tail -n 1| cut -d':' -f1)
  if [ 0$num -ne 0 ]; then
     insertLineInFile "  include $CONFNAME;" $CONFile $(expr $num + 1)
  else echo "  include $CONFNAME;" >>$CONFile
  fi
  printstd "service succefully configured..."
  gitlab-ctl restart
else
  printwrn "service already configured..."
fi


# Do the iptable rules:
mkdir -p /etc/iptables.d/; cat >/etc/iptables.d/$SERVICE <<@@@
# Dynamic file generated by chef
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

-A INPUT -p tcp --dport 80,8080 -j ACCEPT
@@@

printstd "$SERVICE succefully installed."

